### PR TITLE
Unlimited remote args and repo tab when no remote

### PR DESCRIPTION
**Pull request by MichaelDimmitt**
Please review the changes, let me know your thoughts. 

Otherwise, looks good! 
Nice additions Jacob! @MenkeTechnologies.

### CODE REVIEW

**Comment by MenkeTechnologies** [comment]
where is $machine coming from?

**Comment by MenkeTechnologies** [comment]
command grep "$(echo ${argValues// /\\|})" ==>> command grep -E "$(echo ${argValues// /\\|})" . not sure if standard grep supports x|y

**Comment by MichaelDimmitt** [comment]
good catch with `$machine`, updating that change now.

**Comment by MichaelDimmitt** [comment]
not sure if standard grep supports x|y

correct, I was using x\|y to achieve that result.
https://unix.stackexchange.com/a/37316/188491

and I figured out a way to make it much simpler, 
command grep -E "$(echo ${argValues/ /|})"

**Pull request merged**
